// CHE·NU™ Module Declarations
declare module 'framer-motion' {
  export const motion: any;
  export const AnimatePresence: any;
  export const useAnimation: any;
  export const useMotionValue: any;
  export const useTransform: any;
}

declare module 'clsx' {
  export default function clsx(...args: any[]): string;
  export function clsx(...args: any[]): string;
}

declare module 'lucide-react' {
  export const ChevronDown: any;
  export const ChevronUp: any;
  export const ChevronLeft: any;
  export const ChevronRight: any;
  export const X: any;
  export const Check: any;
  export const Search: any;
  export const Settings: any;
  export const User: any;
  export const Menu: any;
  export const Home: any;
  export const Bell: any;
  export const Plus: any;
  export const Minus: any;
  export const Edit: any;
  export const Trash: any;
  export const Save: any;
  export const Upload: any;
  export const Download: any;
  export const File: any;
  export const Folder: any;
  export const Calendar: any;
  export const Clock: any;
  export const MessageSquare: any;
  export const Users: any;
  export const Bot: any;
  export const Zap: any;
  export const Shield: any;
  export const Lock: any;
  export const Unlock: any;
  export const Eye: any;
  export const EyeOff: any;
  export const AlertCircle: any;
  export const AlertTriangle: any;
  export const Info: any;
  export const HelpCircle: any;
  export const MoreHorizontal: any;
  export const MoreVertical: any;
  export const Loader2: any;
  export const RefreshCw: any;
  export const ExternalLink: any;
  export const Copy: any;
  export const Clipboard: any;
  export const Send: any;
  export const Mic: any;
  export const MicOff: any;
  export const Volume2: any;
  export const VolumeX: any;
  export const Play: any;
  export const Pause: any;
  export const Square: any;
  export const Circle: any;
  export const Star: any;
  export const Heart: any;
  export const ThumbsUp: any;
  export const ThumbsDown: any;
  export const Flag: any;
  export const Bookmark: any;
  export const Share: any;
  export const Link: any;
  export const Paperclip: any;
  export const Image: any;
  export const Video: any;
  export const Music: any;
  export const FileText: any;
  export const Code: any;
  export const Terminal: any;
  export const Database: any;
  export const Server: any;
  export const Cloud: any;
  export const Wifi: any;
  export const Globe: any;
  export const Map: any;
  export const MapPin: any;
  export const Navigation: any;
  export const Compass: any;
  export const Sun: any;
  export const Moon: any;
  export const Sunrise: any;
  export const Sunset: any;
  export const CloudRain: any;
  export const Snowflake: any;
  export const Wind: any;
  export const Thermometer: any;
  export const Activity: any;
  export const TrendingUp: any;
  export const TrendingDown: any;
  export const BarChart: any;
  export const PieChart: any;
  export const LineChart: any;
  export const Layers: any;
  export const Layout: any;
  export const Grid: any;
  export const List: any;
  export const Table: any;
  export const Columns: any;
  export const Rows: any;
  export const Maximize: any;
  export const Minimize: any;
  export const Move: any;
  export const RotateCw: any;
  export const RotateCcw: any;
  export const ZoomIn: any;
  export const ZoomOut: any;
  export const Crop: any;
  export const Scissors: any;
  export const Wand2: any;
  export const Sparkles: any;
  export const Brain: any;
  export const Lightbulb: any;
  export const Target: any;
  export const Award: any;
  export const Trophy: any;
  export const Medal: any;
  export const Crown: any;
  export const Gift: any;
  export const Package: any;
  export const ShoppingCart: any;
  export const CreditCard: any;
  export const DollarSign: any;
  export const Percent: any;
  export const Hash: any;
  export const AtSign: any;
  export const Mail: any;
  export const Phone: any;
  export const MessageCircle: any;
  export const Inbox: any;
  export const Archive: any;
  export const Trash2: any;
  export const FolderOpen: any;
  export const FolderPlus: any;
  export const FilePlus: any;
  export const FileCheck: any;
  export const FileX: any;
  export const Printer: any;
  export const Scan: any;
  export const Camera: any;
  export const Aperture: any;
  export const Film: any;
  export const Tv: any;
  export const Monitor: any;
  export const Smartphone: any;
  export const Tablet: any;
  export const Watch: any;
  export const Headphones: any;
  export const Speaker: any;
  export const Radio: any;
  export const Bluetooth: any;
  export const Battery: any;
  export const BatteryCharging: any;
  export const Power: any;
  export const ToggleLeft: any;
  export const ToggleRight: any;
  export const Sliders: any;
  export const Filter: any;
  export const SortAsc: any;
  export const SortDesc: any;
  export const ArrowUp: any;
  export const ArrowDown: any;
  export const ArrowLeft: any;
  export const ArrowRight: any;
  export const ArrowUpRight: any;
  export const ArrowDownLeft: any;
  export const CornerUpLeft: any;
  export const CornerUpRight: any;
  export const CornerDownLeft: any;
  export const CornerDownRight: any;
  export const ChevronsUp: any;
  export const ChevronsDown: any;
  export const ChevronsLeft: any;
  export const ChevronsRight: any;
  export const Repeat: any;
  export const Shuffle: any;
  export const SkipBack: any;
  export const SkipForward: any;
  export const Rewind: any;
  export const FastForward: any;
  export const StopCircle: any;
  export const PlayCircle: any;
  export const PauseCircle: any;
}

// Vite Environment
interface ImportMetaEnv {
  readonly VITE_API_URL: string;
  readonly VITE_WS_URL: string;
  readonly MODE: string;
  readonly DEV: boolean;
  readonly PROD: boolean;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}

// Vitest
declare module 'vitest' {
  export const describe: any;
  export const it: any;
  export const expect: any;
  export const beforeEach: any;
  export const afterEach: any;
  export const vi: any;
}
